services:
  - type: web
    name: sincere-backend
    env: docker
    rootDir: backend-laravel 
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false